### ISSUE TITLE
Infinite looping in .toQuads call

### ISSUE THREAD

**Issue by jeswr** [rubensworks/rdf-object.js#28]
In both cases below, the error `RangeError: Maximum call stack size exceeded` is thrown

```ts
import { RdfObjectLoader } from 'rdf-object';
import { namedNode, quad } from '@rdfjs/data-model';

// Self referential
(async () => {
  const loader = new RdfObjectLoader();
  await loader.importArray([
    quad(namedNode('thing'), namedNode('a'), namedNode('thing'))
  ]);
  const thing = loader.resources['thing'];

  console.log(thing.toQuads());
})();

// Circular reference
(async () => {
  const loader = new RdfObjectLoader();
  await loader.importArray([
    quad(namedNode('jesse'), namedNode('knows'), namedNode('bob')),
    quad(namedNode('bob'), namedNode('knows'), namedNode('jesse')),
  ]);
  const thing = loader.resources['jesse'];

  console.log(thing.toQuads());
})();
```
I also have a [playground link](https://github.com/jeswr/rdf-object-infinite-looping) for this.

Possible solution:
Add each object to a set when you begin to convert it to quads, and check to make sure a nested object is not already in the set before converting it to quads.

**Comment by rubensworks** [comment]
> Add each object to a set when you begin to convert it to quads

Right, this would indeed be the most straightforward solution.
Due to the recursion, this set (or hash) could just be an additional (optional) parameter of `toQuads`.
